module.exports = [

    'Jingle Ball 2021',
    'Merry Little Christmas Party',
    'A December to Remember',
    'Mistletoe Mania',
    'Holidaze 2021',
    'Cocktails and Candy Canes',
    'Holiday Ho-Ho-Hoedown',
    'Jolly Jamboree',
    '1st Annual Goodwill Gala',
    'Blitzen’s Ball',
    'An Evening of Merrymaking',
    '1st Annual Snow Ball',
    'A Not-So-Silent Night',
    'A Christmas Party',
    'Holly Jolly Holiday Party',
    'Jingle Bell Rockout',
    'Gingerbread House Party',
    'A Jolly Good Time',
    'Sugarplum Celebration',
    'Chillin’ Holiday Hangout',
    'Naughty or Nice Party',
    'Miracle on My Street',
    'Jack Frost Jubilee',
    'Holiday Hoopla',
    'Winter Wingding',
    'Festive Fiesta',
    'Candy Cane Cordial',
    'Nutcracker Bash',
    'Winter Wonderland 2021',
    'Santa Soiree',
    '“So Much Humbug” Holiday Party',
    'Ho’s and Bro’s',
    'X-mas X-citement',
    'Tidings & Tinsel',
    'Yuletide Magic',
    'A Very Tipsy Christmas',
    'Rudolf’s Rockin’ Reindeer Bash',
    'Frosty Fest 2021',
    '1st Annual Ugly Sweater Contest',
    'Nasty-Ass Sweater Party',
    'Wacky Tacky Sweater Soiree',
    '1st Annual White Elephant Gift Exchange',
    'Swap ‘Til You Drop 2021',
    'A White Elephant You’ll Never Forget',
    'Who’s Your Santa?',
    'Secret Santa Social',
    'Sleigh Hello to My Little Friend',
    '"Batch Made in Heaven" Cookie Exchange',
    'Cookie Fest 2021',
    
]