module.exports = [
    'abacus',
    'ABC blocks',
    'action figure',
    'ant farm',
    'baseball bat',
    'bear',
    'bicycle',
    'ball',
    'blocks',
    'cap gun',
    'car',
    'cards',
    'chalk board',
    'checkers',
    'chemistry set',
    'chess',
    'clay',
    'construction set',
    'cymbals',
    'dice',
    'dinosaur',
    'doll',
    'doll house',
    'dominoes',
    'dump truck',
    'easel',
    'fire truck',
    'football',
    'globe',
    'gogo',
    'fish',
    'hopscotch',
    'hula hoop',
    'ice skates',
    'jack-in-the-box',
    'jacks',
    'jigsaw puzzle',
    'jump rope',
    'kaleidoscope',
    'Lincoln logs',
    'marbles',
    'marionette',
    'maze',
    'mobile',
    'model car',
    'model train',
    'modeling clay',
    'music box',
    'pong',
    'playhouse',
    'pogo stick',
    'puppet',
    'puzzle',
    'rag doll',
    'rattle',
    'remote-control car',
    'robot',
    'rocking horse',
    'roller skates',
    'rubber duck',
]
